// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2AbQAMcPpVGtK-HPOIWTWJmDuxxL7EIk',
    appId: '1:1030279952802:web:a07f969a6f259e0ae8dafb',
    messagingSenderId: '1030279952802',
    projectId: 'amannewsapp',
    authDomain: 'amannewsapp.firebaseapp.com',
    storageBucket: 'amannewsapp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFYliG6hDsst5paLJFoe4aeumWSmm1HeE',
    appId: '1:1030279952802:android:17cc385c704d3ab2e8dafb',
    messagingSenderId: '1030279952802',
    projectId: 'amannewsapp',
    storageBucket: 'amannewsapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkKg2ixAjFAqlyB2qO2gCuz3yuzAzUO6s',
    appId: '1:1030279952802:ios:69fd4f73ea06654be8dafb',
    messagingSenderId: '1030279952802',
    projectId: 'amannewsapp',
    storageBucket: 'amannewsapp.appspot.com',
    iosClientId: '1030279952802-as9vc6bpk87o4dokrslk7gelb17s3r18.apps.googleusercontent.com',
    iosBundleId: 'com.example.newsapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkKg2ixAjFAqlyB2qO2gCuz3yuzAzUO6s',
    appId: '1:1030279952802:ios:69fd4f73ea06654be8dafb',
    messagingSenderId: '1030279952802',
    projectId: 'amannewsapp',
    storageBucket: 'amannewsapp.appspot.com',
    iosClientId: '1030279952802-as9vc6bpk87o4dokrslk7gelb17s3r18.apps.googleusercontent.com',
    iosBundleId: 'com.example.newsapp',
  );
}
